# Generated by Django 4.2.1 on 2023-05-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на Facebook')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Ссылка на Whats App')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес школы')),
                ('url_address', models.URLField(blank=True, null=True, verbose_name='Ссылка на адрес')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
