# Generated by Django 4.2.1 on 2023-05-21 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_phone', to='settings.setting', verbose_name='Настройка')),
            ],
            options={
                'verbose_name': 'Телефонный номер',
                'verbose_name_plural': 'Телефонные номера',
            },
        ),
    ]
